package com.babas.views.menus;

import com.babas.custom.CustomPane;
import com.babas.custom.TabbedPane;
import com.babas.utilities.Babas;
import com.babas.utilities.Utilities;
import com.babas.views.tabs.TabRecordBoxSesions;
import com.formdev.flatlaf.extras.components.FlatToggleButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenuBoxes {
    private JPanel contentPane;
    private FlatToggleButton btnRecordBoxSessions;
    private TabbedPane tabbedPane;
    private TabRecordBoxSesions tabRecordBoxSesions;

    public MenuBoxes(TabbedPane tabbedPane) {
        this.tabbedPane = tabbedPane;
        $$$setupUI$$$();
        btnRecordBoxSessions.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadRecordBoxSessions();
            }
        });
    }

    public void loadRecordBoxSessions() {
        Utilities.buttonSelected(btnRecordBoxSessions);
        if (tabRecordBoxSesions == null) {
            tabRecordBoxSesions = new TabRecordBoxSesions();
        }
        if (tabbedPane.indexOfTab(tabRecordBoxSesions.getTabPane().getTitle()) == -1) {
            tabRecordBoxSesions = new TabRecordBoxSesions();
            tabRecordBoxSesions.getTabPane().setOption(btnRecordBoxSessions);
            tabbedPane.addTab(tabRecordBoxSesions.getTabPane().getTitle(), tabRecordBoxSesions.getTabPane().getIcon(), tabRecordBoxSesions.getTabPane());
        }
        tabbedPane.setSelectedIndex(tabbedPane.indexOfTab(tabRecordBoxSesions.getTabPane().getTitle()));
    }

    public JPanel getContentPane() {
        btnRecordBoxSessions.setEnabled(Babas.user.getPermitions().isRecordBoxes());
        contentPane.updateUI();
        btnRecordBoxSessions.updateUI();
        return contentPane;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        contentPane = new CustomPane();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 5, 5, 5), -1, 10));
        contentPane.setMaximumSize(new Dimension(130, 2147483647));
        contentPane.setMinimumSize(new Dimension(130, 109));
        contentPane.setPreferredSize(new Dimension(130, 109));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnRecordBoxSessions = new FlatToggleButton();
        btnRecordBoxSessions.setText("<html><center>Historial de Cajas<center></html>");
        contentPane.add(btnRecordBoxSessions, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
