package com.babas.views.menus;

import com.babas.custom.CustomPane;
import com.babas.custom.TabbedPane;
import com.babas.models.Quotation;
import com.babas.models.Reserve;
import com.babas.utilities.Babas;
import com.babas.utilities.Utilities;
import com.babas.views.tabs.*;
import com.formdev.flatlaf.extras.components.FlatToggleButton;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MenuQuotations {
    private FlatToggleButton btnNewQuotation;
    private FlatToggleButton btnRecordQuotations;
    private JPanel contentPane;
    private TabReservesActives tabReservesActives;
    private TabbedPane tabbedPane;
    private TabNewQuotation tabNewQuotation;
    private TabRecordQuotations tabRecordQuotations;

    public MenuQuotations(TabbedPane tabbedPane) {
        this.tabbedPane = tabbedPane;
        $$$setupUI$$$();
        btnNewQuotation.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadNewQuotation();
            }
        });
        btnRecordQuotations.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadRecordQuotations();
            }
        });
    }

    public void loadNewQuotation() {
        btnNewQuotation.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        Utilities.despintarButton(btnRecordQuotations);
        Utilities.buttonSelected(btnNewQuotation);
        if (tabNewQuotation == null) {
            tabNewQuotation = new TabNewQuotation(new Quotation());
        }
        if (tabbedPane.indexOfTab(tabNewQuotation.getTabPane().getTitle()) == -1) {
            tabNewQuotation = new TabNewQuotation(new Quotation());
            tabNewQuotation.getTabPane().setOption(btnNewQuotation);
            tabbedPane.addTab(tabNewQuotation.getTabPane().getTitle(), tabNewQuotation.getTabPane().getIcon(), tabNewQuotation.getTabPane());
        }
        tabbedPane.setSelectedIndex(tabbedPane.indexOfTab(tabNewQuotation.getTabPane().getTitle()));
        btnNewQuotation.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    public void loadRecordQuotations() {
        btnRecordQuotations.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        Utilities.despintarButton(btnNewQuotation);
        Utilities.buttonSelected(btnRecordQuotations);
        if (tabRecordQuotations == null) {
            tabRecordQuotations = new TabRecordQuotations();
        }
        if (tabbedPane.indexOfTab(tabRecordQuotations.getTabPane().getTitle()) == -1) {
            tabRecordQuotations = new TabRecordQuotations();
            tabRecordQuotations.getTabPane().setOption(btnRecordQuotations);
            tabbedPane.addTab(tabRecordQuotations.getTabPane().getTitle(), tabRecordQuotations.getTabPane().getIcon(), tabRecordQuotations.getTabPane());
        }
        tabbedPane.setSelectedIndex(tabbedPane.indexOfTab(tabRecordQuotations.getTabPane().getTitle()));
        btnRecordQuotations.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    public JPanel getContentPane() {
        btnRecordQuotations.setEnabled(Babas.user.getPermitions().isReservesActives());
        btnNewQuotation.setEnabled(Babas.user.getPermitions().isRecordReserves());
        contentPane.updateUI();
        btnRecordQuotations.updateUI();
        btnNewQuotation.updateUI();
        return contentPane;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        contentPane = new CustomPane();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane.setLayout(new GridLayoutManager(3, 1, new Insets(10, 5, 5, 5), -1, 10));
        contentPane.setMaximumSize(new Dimension(130, 2147483647));
        contentPane.setMinimumSize(new Dimension(130, 149));
        contentPane.setPreferredSize(new Dimension(130, 149));
        final Spacer spacer1 = new Spacer();
        contentPane.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        btnNewQuotation = new FlatToggleButton();
        btnNewQuotation.setText("<html><center>Nueva cotización<center></html>");
        contentPane.add(btnNewQuotation, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnRecordQuotations = new FlatToggleButton();
        btnRecordQuotations.setText("<html><center>Historial de cotizaciones<center></html>");
        contentPane.add(btnRecordQuotations, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}